version: '3'
services:
  altiscope-memo-app-nginx:
    container_name: altiscope-memo-app-nginx
    tty: true
    networks:
      - altiscope-network
    image: nginx:latest
    expose:
      - 8902
    ports:
      - "8902:80"
    environment:
      - PORT=8902
    volumes:
      - "../../src:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    command: /bin/sh -c "exec nginx -g 'daemon off;'"
networks:
  altiscope-network:
    driver: bridge