version: '3'
services:
  altiscope-memo-app:
    container_name: altiscope-memo-app
    networks:
      - altiscope-network
    tty: true
    build:
      context: '../../src'
      dockerfile: Dockerfile
    expose:
      - 8902
    ports:
      - 8902:8902
    environment:
      - PORT=8902
networks:
  altiscope-network:
    driver: bridge