version: '3'
services:
  altiscope-memo-app:
    container_name: altiscope-memo-app
    networks:
      - altiscope-network
    tty: true
    build:
      context: '../../src'
      dockerfile: Dockerfile
    ports:
      - 8900:8900
    environment:
      - PORT=8900
networks:
  altiscope-network:
    driver: bridge